---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "AYO API Documentation"
host: "172.24.252.167:10010"
basePath: "/ayo"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /homepage:
    post:
      tags:
      - "homepage"
      summary: "get homepage based on specified geo"
      description: ""
      operationId: "homepage"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "homepage geo that might contain lat-lon, geoId, landmarkId.\
          \ if null given, default will be Jakarta"
        required: true
        schema:
          $ref: "#/definitions/HomepageRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HomepageResponse"
        400:
          description: "Invalid geo"
      x-swagger-router-controller: "Homepage"
  /poi:
    post:
      tags:
      - "poi"
      summary: "get poi detail based on poi id"
      description: ""
      operationId: "poi"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/POIRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/POIResponse"
        400:
          description: "Invalide POI id"
      x-swagger-router-controller: "Poi"
  /location:
    post:
      tags:
      - "location"
      summary: "get the location"
      description: ""
      operationId: "location"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/LocationRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/LocationResponse"
        400:
          description: "Invalide  query"
      x-swagger-router-controller: "Location"
  /omnisearch:
    post:
      tags:
      - "omnisearch"
      summary: "get the omnisearch"
      description: ""
      operationId: "omnisearch"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/OmniSearchRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/OmniSearchResponse"
        400:
          description: "Invalide  query"
      x-swagger-router-controller: "Omnisearch"
  /search/availablefilter:
    post:
      tags:
      - "searchresult"
      summary: "get search result page spec"
      description: "Api Call to get Search Result Spec; like filter and sort"
      operationId: "search_spec"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/AvailableFilterRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/AvailableFilterResponse"
        400:
          description: "Invalide  query"
  /search/list:
    post:
      tags:
      - "searchresult"
      summary: "get search result"
      description: "Api Call to get Search Result"
      operationId: "search_list"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/SearchResultRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SearchResultResponse"
        400:
          description: "Invalide  query"
  /search/further:
    post:
      tags:
      - "searchresult"
      summary: "get search result further away result"
      description: "Api Call to get Search Result for Further Away Result"
      operationId: "search_further"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/SearchResultRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SearchResultResponse"
        400:
          description: "Invalide  query"
  /gallery:
    post:
      tags:
      - "gallery"
      summary: "get photo gallery"
      description: "Get All Photos and its component in certain restaurants"
      operationId: "gallery"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/GalleryRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GalleryResponse"
        400:
          description: "Invalide  query"
          
  /glossary:
    post:
      tags:
      - "glossary"
      summary: "Get glossary based on specified geo"
      description: ""
      operationId: "glossary"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User geo that might contain lat-lon, geoId, landmarkId.\
          \ if null given, default will be Jakarta"
        required: false
        schema:
          $ref: "#/definitions/GlossaryPageRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GlossaryPageResponse"
            
definitions:
  GeoDisplay:
    type: "object"
    required:
    - "id"
    - "locationType"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "Jakarta"
      locationType:
        type: "string"
        example: "GEO"
        description: "Type of location"
        enum:
        - "GEO"
        - "LANDMARK"
    example:
      name: "Jakarta"
      locationType: "GEO"
      id: 0
  RestaurantTile:
    type: "object"
    required:
    - "id"
    - "imageUrl"
    - "locationLabel"
    - "name"
    properties:
      id:
        type: "string"
        example: "123"
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      name:
        type: "string"
        example: "Bureau Cafe"
      locationLabel:
        type: "string"
        example: "Central Park, Slipi"
      cuisineType:
        type: "string"
        example: "Western"
      ratingDisplay:
        $ref: "#/definitions/RatingDisplay"
    example:
      ratingDisplay:
        rating: 4.5999999999999996447286321199499070644378662109375
        ratingColor:
          r: 153
          b: 152
          g: 37
      imageUrl: "http://tny.im/jA-"
      name: "Bureau Cafe"
      locationLabel: "Central Park, Slipi"
      id: "123"
      cuisineType: "Western"
  RatingDisplay:
    type: "object"
    required:
    - "rating"
    - "ratingColor"
    properties:
      rating:
        type: "number"
        example: 4.5999999999999996447286321199499070644378662109375
      ratingColor:
        $ref: "#/definitions/Color"
    example:
      rating: 4.5999999999999996447286321199499070644378662109375
      ratingColor:
        r: 153
        b: 152
        g: 37
  Banner:
    type: "object"
    required:
    - "deeplink"
    - "imageUrl"
    properties:
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      deeplink:
        type: "string"
        example: "http://heyayo.id"
    example:
      imageUrl: "http://tny.im/jA-"
      deeplink: "http://heyayo.id"
  NearbyRestaurantDisplay:
    type: "object"
    required:
    - "imageUrl"
    - "label"
    properties:
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      label:
        type: "string"
        example: "See restaurant around me"
    example:
      imageUrl: "http://tny.im/jA-"
      label: "See restaurant around me"
  DishTile:
    type: "object"
    required:
    - "id"
    - "imageUrl"
    properties:
      id:
        type: "string"
        example: "PIZZA"
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
    example:
      imageUrl: "http://tny.im/jA-"
      id: "PIZZA"
  Section:
    type: "object"
    required:
    - "dishes"
    - "groupType"
    - "restaurants"
    - "title"
    properties:
      title:
        type: "string"
        example: "Restoran di Jakarta"
      groupType:
        type: "string"
        example: "RESTAURANT"
        enum:
        - "RESTAURANT"
        - "DISH"
        - "CUISINE"
      restaurants:
        type: "array"
        items:
          $ref: "#/definitions/RestaurantTile"
      dishes:
        type: "array"
        items:
          $ref: "#/definitions/DishTile"
    example:
      groupType: "RESTAURANT"
      restaurants:
      - ratingDisplay:
          rating: 4.5999999999999996447286321199499070644378662109375
          ratingColor:
            r: 153
            b: 152
            g: 37
        imageUrl: "http://tny.im/jA-"
        name: "Bureau Cafe"
        locationLabel: "Central Park, Slipi"
        id: "123"
        cuisineType: "Western"
      - ratingDisplay:
          rating: 4.5999999999999996447286321199499070644378662109375
          ratingColor:
            r: 153
            b: 152
            g: 37
        imageUrl: "http://tny.im/jA-"
        name: "Bureau Cafe"
        locationLabel: "Central Park, Slipi"
        id: "123"
        cuisineType: "Western"
      dishes:
      - imageUrl: "http://tny.im/jA-"
        id: "PIZZA"
      - imageUrl: "http://tny.im/jA-"
        id: "PIZZA"
      title: "Restoran di Jakarta"
  HomepageDataResponse:
    type: "object"
    required:
    - "banners"
    - "geoDisplay"
    - "sections"
    properties:
      geoDisplay:
        $ref: "#/definitions/GeoDisplay"
      banners:
        type: "array"
        items:
          $ref: "#/definitions/Banner"
      nearbyRestaurantDisplay:
        $ref: "#/definitions/NearbyRestaurantDisplay"
      sections:
        type: "array"
        items:
          $ref: "#/definitions/Section"
    example:
      geoDisplay:
        name: "Jakarta"
        locationType: "GEO"
        id: 0
      banners:
      - imageUrl: "http://tny.im/jA-"
        deeplink: "http://heyayo.id"
      - imageUrl: "http://tny.im/jA-"
        deeplink: "http://heyayo.id"
      nearbyRestaurantDisplay:
        imageUrl: "http://tny.im/jA-"
        label: "See restaurant around me"
      sections:
      - groupType: "RESTAURANT"
        restaurants:
        - ratingDisplay:
            rating: 4.5999999999999996447286321199499070644378662109375
            ratingColor:
              r: 153
              b: 152
              g: 37
          imageUrl: "http://tny.im/jA-"
          name: "Bureau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
          cuisineType: "Western"
        - ratingDisplay:
            rating: 4.5999999999999996447286321199499070644378662109375
            ratingColor:
              r: 153
              b: 152
              g: 37
          imageUrl: "http://tny.im/jA-"
          name: "Bureau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
          cuisineType: "Western"
        dishes:
        - imageUrl: "http://tny.im/jA-"
          id: "PIZZA"
        - imageUrl: "http://tny.im/jA-"
          id: "PIZZA"
        title: "Restoran di Jakarta"
      - groupType: "RESTAURANT"
        restaurants:
        - ratingDisplay:
            rating: 4.5999999999999996447286321199499070644378662109375
            ratingColor:
              r: 153
              b: 152
              g: 37
          imageUrl: "http://tny.im/jA-"
          name: "Bureau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
          cuisineType: "Western"
        - ratingDisplay:
            rating: 4.5999999999999996447286321199499070644378662109375
            ratingColor:
              r: 153
              b: 152
              g: 37
          imageUrl: "http://tny.im/jA-"
          name: "Bureau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
          cuisineType: "Western"
        dishes:
        - imageUrl: "http://tny.im/jA-"
          id: "PIZZA"
        - imageUrl: "http://tny.im/jA-"
          id: "PIZZA"
        title: "Restoran di Jakarta"
  GeoLocation:
    type: "object"
    required:
    - "lat"
    - "lon"
    properties:
      lat:
        type: "number"
        example: 23.449999999999999289457264239899814128875732421875
      lon:
        type: "number"
        example: 68.4500000000000028421709430404007434844970703125
    example:
      lon: 68.4500000000000028421709430404007434844970703125
      lat: 23.449999999999999289457264239899814128875732421875
  HomepageRequest:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/GeoRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        geoLocation:
          lon: 68.4500000000000028421709430404007434844970703125
          lat: 23.449999999999999289457264239899814128875732421875
        geoDisplay:
          name: "Jakarta"
          locationType: "GEO"
          id: 0
      context:
        session: "session"
        clientInterface: "clientInterface"
  ContextRequest:
    type: "object"
    required:
    - "clientInterface"
    properties:
      session:
        type: "string"
      clientInterface:
        type: "string"
    example:
      session: "session"
      clientInterface: "clientInterface"
  ContextResponse:
    type: "object"
    properties:
      session:
        type: "string"
    example:
      session: "session"
  GeoRequestData:
    type: "object"
    required:
    - "geoDisplay"
    - "geoLocation"
    properties:
      geoDisplay:
        $ref: "#/definitions/GeoDisplay"
      geoLocation:
        $ref: "#/definitions/GeoLocation"
    example:
      geoLocation:
        lon: 68.4500000000000028421709430404007434844970703125
        lat: 23.449999999999999289457264239899814128875732421875
      geoDisplay:
        name: "Jakarta"
        locationType: "GEO"
        id: 0
  HomepageResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/HomepageDataResponse"
      context:
        $ref: "#/definitions/ContextResponse"
    example:
      data:
        geoDisplay:
          name: "Jakarta"
          locationType: "GEO"
          id: 0
        banners:
        - imageUrl: "http://tny.im/jA-"
          deeplink: "http://heyayo.id"
        - imageUrl: "http://tny.im/jA-"
          deeplink: "http://heyayo.id"
        nearbyRestaurantDisplay:
          imageUrl: "http://tny.im/jA-"
          label: "See restaurant around me"
        sections:
        - groupType: "RESTAURANT"
          restaurants:
          - ratingDisplay:
              rating: 4.5999999999999996447286321199499070644378662109375
              ratingColor:
                r: 153
                b: 152
                g: 37
            imageUrl: "http://tny.im/jA-"
            name: "Bureau Cafe"
            locationLabel: "Central Park, Slipi"
            id: "123"
            cuisineType: "Western"
          - ratingDisplay:
              rating: 4.5999999999999996447286321199499070644378662109375
              ratingColor:
                r: 153
                b: 152
                g: 37
            imageUrl: "http://tny.im/jA-"
            name: "Bureau Cafe"
            locationLabel: "Central Park, Slipi"
            id: "123"
            cuisineType: "Western"
          dishes:
          - imageUrl: "http://tny.im/jA-"
            id: "PIZZA"
          - imageUrl: "http://tny.im/jA-"
            id: "PIZZA"
          title: "Restoran di Jakarta"
        - groupType: "DISH"
          restaurants:
          - ratingDisplay:
              rating: 4.5999999999999996447286321199499070644378662109375
              ratingColor:
                r: 153
                b: 152
                g: 37
            imageUrl: "http://tny.im/jA-"
            name: "Bureau Cafe"
            locationLabel: "Central Park, Slipi"
            id: "123"
            cuisineType: "Western"
          - ratingDisplay:
              rating: 4.5999999999999996447286321199499070644378662109375
              ratingColor:
                r: 153
                b: 152
                g: 37
            imageUrl: "http://tny.im/jA-"
            name: "Bureau Cafe"
            locationLabel: "Central Park, Slipi"
            id: "123"
            cuisineType: "Western"
          dishes:
          - imageUrl: "http://tny.im/jA-"
            id: "PIZZA"
          - imageUrl: "http://tny.im/jA-"
            id: "PIZZA"
          title: "Restoran di Jakarta"
      context:
        session: "session"
  HourMinute:
    type: "object"
    required:
    - "hour"
    properties:
      hour:
        type: "integer"
        example: 7
        minimum: 0
        maximum: 23
      minutes:
        type: "integer"
        example: 0
        minimum: 0
        maximum: 59
    example:
      hour: 7
      minutes: 0
  OpenHour:
    type: "object"
    required:
    - "closed"
    - "isToday"
    - "operationHours"
    - "weekDay"
    properties:
      weekDay:
        type: "string"
        example: "SUNDAY"
        enum:
        - "SUNDAY"
        - "MONDAY"
        - "TUESDAY"
        - "WEDNESDAY"
        - "THURSDAY"
        - "FRIDAY"
        - "SATURDAY"
      operationHours:
        type: "array"
        items:
          $ref: "#/definitions/OperationHour"
      closed:
        type: "boolean"
        example: false
      isToday:
        type: "boolean"
        example: false
    example:
      weekDay: "SUNDAY"
      operationHours:
      - closeTime:
          hour: 7
          minutes: 0
        openTime:
          hour: 7
          minutes: 0
      - closeTime:
          hour: 7
          minutes: 0
        openTime:
          hour: 7
          minutes: 0
      isToday: false
      closed: false
  OperationHour:
    type: "object"
    required:
    - "closeTime"
    - "openTime"
    properties:
      openTime:
        $ref: "#/definitions/HourMinute"
      closeTime:
        $ref: "#/definitions/HourMinute"
    example:
      closeTime:
        hour: 7
        minutes: 0
      openTime:
        hour: 7
        minutes: 0
  Tag:
    type: "object"
    required:
    - "imageUrl"
    - "label"
    properties:
      label:
        type: "string"
        example: "Historical Building"
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
    example:
      imageUrl: "http://tny.im/jA-"
      label: "Historical Building"
  BestKnownFor:
    type: "object"
    required:
    - "description"
    properties:
      description:
        type: "string"
        example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas\
          \ eu eros ac massa interdum mattis. Integer feugiat tortor sit amet ligula\
          \ sodales, vel mollis sem laoreet. Pellentesque quis nibh vitae risus gravida\
          \ cursus. Maecenas congue dictum consectetur. Fusce in nibh ut mi consectetur\
          \ pretium. "
      tags:
        type: "array"
        items:
          $ref: "#/definitions/Tag"
    example:
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas\
        \ eu eros ac massa interdum mattis. Integer feugiat tortor sit amet ligula\
        \ sodales, vel mollis sem laoreet. Pellentesque quis nibh vitae risus gravida\
        \ cursus. Maecenas congue dictum consectetur. Fusce in nibh ut mi consectetur\
        \ pretium. "
      tags:
      - imageUrl: "http://tny.im/jA-"
        label: "Historical Building"
      - imageUrl: "http://tny.im/jA-"
        label: "Historical Building"
  LocationInfo:
    type: "object"
    required:
    - "address"
    - "geoLocation"
    - "label"
    properties:
      label:
        type: "string"
        example: "PIK Avenue, 2nd Floor"
      address:
        type: "string"
        example: "Jalan S Parman Kav 77, Slipi, Jakarta Barat."
      geoLocation:
        $ref: "#/definitions/GeoLocation"
    example:
      address: "Jalan S Parman Kav 77, Slipi, Jakarta Barat."
      geoLocation:
        lon: 68.4500000000000028421709430404007434844970703125
        lat: 23.449999999999999289457264239899814128875732421875
      label: "PIK Avenue, 2nd Floor"
  FeatureFacility:
    type: "object"
    required:
    - "available"
    - "iconImageUrl"
    - "label"
    properties:
      iconImageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      label:
        type: "string"
        example: "Air Conditioned"
      available:
        type: "boolean"
        example: true
    example:
      iconImageUrl: "http://tny.im/jA-"
      available: true
      label: "Air Conditioned"
  RestaurantNearby:
    type: "object"
    required:
    - "id"
    - "imageUrl"
    - "locationLabel"
    - "name"
    - "restaurantType"
    properties:
      id:
        type: "string"
        example: "123"
      name:
        type: "string"
        example: "Bereau Cafe"
      locationLabel:
        type: "string"
        example: "Central Park, Slipi"
      restaurantType:
        type: "string"
        example: "Western"
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
    example:
      restaurantType: "Western"
      imageUrl: "http://tny.im/jA-"
      name: "Bereau Cafe"
      locationLabel: "Central Park, Slipi"
      id: "123"
  Photo:
    type: "object"
    required:
    - "category"
    - "imageUrl"
    - "mainSubcategory"
    - "subcategories"
    properties:
      imageUrl:
        type: "string"
        example: "http://tny.im/jA-"
      category:
        type: "string"
        example: "AMBIENCE"
      mainSubcategory:
        type: "string"
        example: "Indoor seating"
      subcategories:
        type: "array"
        items:
          type: "string"
    example:
      imageUrl: "http://tny.im/jA-"
      category: "AMBIENCE"
      mainSubcategory: "Indoor Seating"
      subcategories:
      - "subcategories"
      - "subcategories"
  PhotoGroupDisplay:
    type: "object"
    required:
        - "photos"
        - "tab"
    properties:
        photos:
            type: "array"
            items:
                $ref: "#/definitions/Photo"
        tab:
            type: "string"
            example: "Menu"
    example:
        tab: "Menu"
        photos:
        - imageUrl: "http://tny.im/jA-"
          category: "AMBIENCE"
          mainSubcategory: "Indoor seating"
          subcategories:
            - "subcategories"
            - "subcategories"
        - imageUrl: "http://tny.im/jA-"
          category: "AMBIENCE"
          mainSubcategory: "Indoor seating"
          subcategories:
            - "subcategories"
            - "subcategories"
  Color:
    type: "object"
    required:
    - "b"
    - "g"
    - "r"
    properties:
      r:
        type: "integer"
        minimum: 0
        maximum: 255
      g:
        type: "integer"
        minimum: 0
        maximum: 255
      b:
        type: "integer"
        minimum: 0
        maximum: 255
    example:
      r: 153
      b: 152
      g: 37
  POIStatus:
    type: "object"
    required:
    - "status"
    - "statusLabel"
    properties:
      status:
        type: "string"
        example: "PERMANENTLY_CLOSED"
        enum:
        - "NEW"
        - "COMING_SOON"
        - "TEMP_CLOSED"
        - "PERMANENTLY_CLOSED"
      statusLabel:
        type: "string"
        example: "Opening again at 11 dec 2019"
    example:
      statusLabel: "Opening again at 11 dec 2019"
      status: "PERMANENTLY_CLOSED"
  Price:
    type: "object"
    required:
    - "priceLabel"
    properties:
      priceLabel:
        type: "string"
        example: "Around Rp 100.000 per person"
      priceDetail:
        type: "string"
        example: "price for 1 dish + 1 beverages"
    example:
      priceDetail: "price for 1 dish + 1 beverages"
      priceLabel: "Around Rp 100.000 per person"
  POIResponseData:
    type: "object"
    required:
    - "cuisineDishTypes"
    - "featureFacilities"
    - "id"
    - "poiPhotosList"
    - "locationInfo"
    - "mainCuisine"
    - "mainDish"
    - "mainRestaurantType"
    - "name"
    - "openHourToday"
    - "openHours"
    - "phoneNumbers"
    - "photo"
    - "menu"
    - "price"
    - "restaurantTypes"
    properties:
      id:
        type: "string"
        example: "123"
      name:
        type: "string"
        example: "Chir Chir fusion Chicken"
      bestKnownFor:
        $ref: "#/definitions/BestKnownFor"
      locationInfo:
        $ref: "#/definitions/LocationInfo"
      mainRestaurantType:
        type: "string"
        example: "Casual Dining"
      mainCuisine:
        type: "string"
        example: "Korean"
      mainDish:
        type: "string"
        example: "Fried Chicken"
      POIstatus:
        $ref: "#/definitions/POIStatus"
      price:
        $ref: "#/definitions/Price"
      openHourToday:
        $ref: "#/definitions/OpenHour"
      openHours:
        type: "array"
        items:
          $ref: "#/definitions/OpenHour"
      restaurantTypes:
        type: "array"
        items:
          type: "string"
      cuisineDishTypes:
        type: "array"
        items:
          type: "string"
      highlightedFeatureFacilities:
        type: "array"
        items:
          $ref: "#/definitions/FeatureFacility"
      featureFacilities:
        type: "array"
        items:
          $ref: "#/definitions/FeatureFacility"
      phoneNumbers:
        type: "array"
        items:
          type: "string"
      paymentMethods:
        type: "array"
        items:
          $ref: "#/definitions/FeatureFacility"
      restaurantNearbies:
        type: "array"
        items:
          $ref: "#/definitions/RestaurantNearby"
      photo:
        $ref: "#/definitions/PhotoGroupDisplay"
      menu:
        $ref: "#/definitions/PhotoGroupDisplay"
      poiPhotosList:
        type: "array"
        items:
          type: "string"
    example:
      openHours:
      - weekDay: "SUNDAY"
        operationHours:
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        isToday: false
        closed: false
      - weekDay: "SUNDAY"
        operationHours:
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        isToday: false
        closed: false
      bestKnownFor:
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas\
          \ eu eros ac massa interdum mattis. Integer feugiat tortor sit amet ligula\
          \ sodales, vel mollis sem laoreet. Pellentesque quis nibh vitae risus gravida\
          \ cursus. Maecenas congue dictum consectetur. Fusce in nibh ut mi consectetur\
          \ pretium. "
        tags:
        - imageUrl: "http://tny.im/jA-"
          label: "Historical Building"
        - imageUrl: "http://tny.im/jA-"
          label: "Historical Building"
      locationInfo:
        address: "Jalan S Parman Kav 77, Slipi, Jakarta Barat."
        geoLocation:
          lon: 68.4500000000000028421709430404007434844970703125
          lat: 23.449999999999999289457264239899814128875732421875
        label: "PIK Avenue, 2nd Floor"
      restaurantNearbies:
      - restaurantType: "Western"
        imageUrl: "http://tny.im/jA-"
        name: "Bereau Cafe"
        locationLabel: "Central Park, Slipi"
        id: "123"
      - restaurantType: "Western"
        imageUrl: "http://tny.im/jA-"
        name: "Bereau Cafe"
        locationLabel: "Central Park, Slipi"
        id: "123"
      mainCuisine: "Korean"
      POIstatus:
        statusLabel: "Opening again at 11 dec 2019"
        status: "PERMANENTLY_CLOSED"
      mainDish: "Fried Chicken"
      mainRestaurantType: "Casual Dining"

      phoneNumbers:
      - "phoneNumbers"
      - "phoneNumbers"
      restaurantTypes:
      - "restaurantTypes"
      - "restaurantTypes"
      poiPhotosList:
      - "imageUrlList"
      - "imageUrlList"
      featureFacilities:
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      price:
        priceDetail: "price for 1 dish + 1 beverages"
        priceLabel: "Around Rp 100.000 per person"
      paymentMethods:
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      name: "Chir Chir fusion Chicken"
      id: "123"
      openHourToday:
        weekDay: "SUNDAY"
        operationHours:
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        - closeTime:
            hour: 7
            minutes: 0
          openTime:
            hour: 7
            minutes: 0
        isToday: false
        closed: false
      highlightedFeatureFacilities:
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
      - iconImageUrl: "http://tny.im/jA-"
        available: true
        label: "Air Conditioned"
  POIRequestData:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
        example: "123"
    example:
      id: "123"
  POIResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/POIResponseData"
      context:
        $ref: "#/definitions/ContextResponse"
    example:
      data:
        openHours:
        - weekDay: "SUNDAY"
          operationHours:
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          isToday: false
          closed: false
        - weekDay: "SUNDAY"
          operationHours:
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          isToday: false
          closed: false
        bestKnownFor:
          description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas\
            \ eu eros ac massa interdum mattis. Integer feugiat tortor sit amet ligula\
            \ sodales, vel mollis sem laoreet. Pellentesque quis nibh vitae risus\
            \ gravida cursus. Maecenas congue dictum consectetur. Fusce in nibh ut\
            \ mi consectetur pretium. "
          tags:
          - imageUrl: "http://tny.im/jA-"
            label: "Historical Building"
          - imageUrl: "http://tny.im/jA-"
            label: "Historical Building"
        locationInfo:
          address: "Jalan S Parman Kav 77, Slipi, Jakarta Barat."
          geoLocation:
            lon: 68.4500000000000028421709430404007434844970703125
            lat: 23.449999999999999289457264239899814128875732421875
          label: "PIK Avenue, 2nd Floor"
        restaurantNearbies:
        - restaurantType: "Western"
          imageUrl: "http://tny.im/jA-"
          name: "Bereau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
        - restaurantType: "Western"
          imageUrl: "http://tny.im/jA-"
          name: "Bereau Cafe"
          locationLabel: "Central Park, Slipi"
          id: "123"
        mainCuisine: "Korean"
        POIstatus:
          statusLabel: "Opening again at 11 dec 2019"
          status: "PERMANENTLY_CLOSED"
        mainDish: "Fried Chicken"
        mainRestaurantType: "Casual Dining"
        photo:
          tab: "ALL"
          photos:
          - imageUrl: "http://tny.im/jA-"
            category: "AMBIENCE"
            mainSubcategory: "Indoor seating"
            subcategories:
            - "subcategories"
            - "subcategories"
          - imageUrl: "http://tny.im/jA-"
            category: "AMBIENCE"
            mainSubcategory: "Indoor seating"
            subcategories:
            - "subcategories"
            - "subcategories"
        phoneNumbers:
        - "phoneNumbers"
        - "phoneNumbers"
        restaurantTypes:
        - "restaurantTypes"
        - "restaurantTypes"
        poiPhotosList:
        - "imageUrlList"
        - "imageUrlList"
        featureFacilities:
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        price:
          priceDetail: "price for 1 dish + 1 beverages"
          priceLabel: "Around Rp 100.000 per person"
        paymentMethods:
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        name: "Chir Chir fusion Chicken"
        id: "123"
        openHourToday:
          weekDay: "SUNDAY"
          operationHours:
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          - closeTime:
              hour: 7
              minutes: 0
            openTime:
              hour: 7
              minutes: 0
          isToday: false
          closed: false
        highlightedFeatureFacilities:
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        - iconImageUrl: "http://tny.im/jA-"
          available: true
          label: "Air Conditioned"
        menu:
          tab: "Menu"
          photos:
          - imageUrl: "http://tny.im/jA-"
            category: "AMBIENCE"
            mainSubcategory: "Indoor seating"
            subcategories:
            - "subcategories"
            - "subcategories"
          - imageUrl: "http://tny.im/jA-"
            category: "AMBIENCE"
            mainSubcategory: "Indoor seating"
            subcategories:
            - "subcategories"
            - "subcategories"
        cuisineDishTypes:
        - "cuisineDishTypes"
        - "cuisineDishTypes"
      context:
        session: "session"
  POIRequest:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/POIRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        id: "123"
      context:
        session: "session"
        clientInterface: "clientInterface"
  LocationRequestData:
    type: "object"
    required:
    - "query"
    properties:
      query:
        type: "string"
    example:
      query: "123"
  LocationRequest:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/LocationRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        query: "slipi"
      context:
        session: "session"
        clientInterface: "clientInterface"
  LocationResponseData:
    type: "object"
    required:
    - "locations"
    properties:
      locations:
        type: "array"
        items:
          type: "object"
          properties:
            geoDisplay:
              $ref: "#/definitions/GeoDisplay"
  LocationResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/LocationResponseData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        locations:
          - geoDisplay:
              name: "Jakarta, Indonesia"
              locationType: "GEO"
              id: 1
          - geoDisplay:
              name: "Atma Jaya, Jakarta"
              locationType: "GEO"
              id: 2
          - geoDisplay:
              name: "Wisma 77 Tower 2, Jakarta"
              locationType: "GEO"
              id: 3
          - geoDisplay:
              name: "Taman Wisata Jaya Ancol"
              locationType: "GEO"
              id: 4
          - geoDisplay:
              name: "Ragunan"
              locationType: "GEO"
              id: 5
          - geoDisplay:
              name: "Gedung Citicon, Slipi"
              locationType: "GEO"
              id: 6
          - geoDisplay:
              name: "Menara Peninsula"
              locationType: "GEO"
              id: 7
      context:
        session: "session"
        clientInterface: "clientInterface"
  MultiCurrencyValue:
    type: "object"
    required:
    - "currency"
    - "amount"
    - "numOfDecimalPoint"
    properties:
      currency:
        type: "string"
        example: "IDR"
      amount:
        type: "number"
        example: 100000
      numOfDecimalPoint:
        type: "integer"
        format: "int64"
        example: "3"
    example:
      currency: "IDR"
      amount: 100000
      numOfDecimalPoint: 0
  SearchResultRequest:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/SearchResultRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
  SearchResultRequestData:
    type: "object"
    required: 
      - "geoDisplay"
      - "geoLocation"
    properties:
      geoDisplay: 
        $ref: "#/definitions/GeoDisplay"
      geoLocation:
        $ref: "#/definitions/GeoLocation"
      filter:
        $ref: "#/definitions/SearchResultFilterBase"
      sort:
        type: "string"
        example: "Popularity"
      limit:
        type: "integer"
        format: "int64"
      skip:
        type: "integer"
        format: "int64"
  SearchResultFilterBase:
    type: "object"
    required:
    - "quickFilters"
    - "ratings"
    - "prices"
    - "types"
    - "cuisines"
    - "dishes"
    - "dietaries"
    - "facilities"
    properties:
      quickFilters:
       type: "array"
       items:
          type: "string"
      ratings:
       type: "array"
       items:
          type: "string"
      prices:
       type: "object"
       properties: 
        minPrice:
          $ref: "#/definitions/MultiCurrencyValue"
        maxPrice: 
          $ref: "#/definitions/MultiCurrencyValue"        
      types:
       type: "array"
       items:
          type: "string"
      cuisines:
       type: "array"
       items:
          type: "string"
      dishes:
       type: "array"
       items:
          type: "string"
      dietaries:
       type: "array"
       items:
          type: "string"
      facilities:
       type: "array"
       items:
          type: "string"
  AvailableFilterRequest:        
    type: "object"
    required:
    - "context"
    properties:
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      context:
        session: "session"
        clientInterface: "clientInterface"
  AvailableFilterResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/AvailableFilterData"
      context:
        $ref: "#/definitions/ContextResponse"
  AvailableFilterData:
    type: "object"
    required:
    - "filterSpec"
    - "sortSpec"
    properties:
      filterSpec:
        $ref: "#/definitions/AvailableFilterSpec"
      sortSpec:
        type: "array"
        items:
          $ref: "#/definitions/AvailableSortSpec"
  AvailableSortSpec:
    type: "object"
    required:
    - "id"
    - "label"
    properties:
      id:
        type: "string"
        example: "lowest"
      label:
        type: "string"
        example: "Sort By: Lowest to Highest"
    example:
      id: "lowest"
      label: "Sort By: Lowest to Highest"
  AvailableFilterSpec:
    type: "object"
    required:
    - "quickFilters"
    - "ratings"
    - "prices"
    - "types"
    - "cuisines"
    - "dishes"
    - "dietaries"
    - "facilities"
    properties:
      quickFilters:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      ratings:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      prices:
        type: "object"
        properties:
          minPrice:
            $ref: "#/definitions/MultiCurrencyValue"
          maxPrice: 
            $ref: "#/definitions/MultiCurrencyValue"
      types:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      cuisines:
        type: "array" 
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      dishes:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      dietaries:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"
      facilities:
        type: "array"
        items:
          $ref: "#/definitions/SearchResultFilterItem"  
  SearchResultFilterItem:
    type: "object"
    required:
    - "id"
    - "label"
    properties:
      id:
        type: "string"
        example: "open"
      label:
        type: "string"
        example: "Open Now"
    example:
      id: "open"
      label: "Open 24 Hours"
  SearchResultResponse:
    type: "object"
    required:
    - "context"
    - "data"
    properties:
      data:
        $ref: "#/definitions/SearchResultDataResponse"
      context:
        $ref: "#/definitions/ContextResponse"
  SearchResultDataResponse:
    type: "object"
    required:
    - "restaurantList"
    properties:
      restaurantList:
        type: "array"
        items:
          $ref: "#/definitions/RestaurantCard"
  RestaurantCard:
    type: "object"
    required:
    - "id"
    - "name"
    - "mainType"
    - "mainCuisine"
    - "address"
    - "status"
    properties:
      id:
        type: "string"
        example: "123"
      name:
        type: "string"
      mainType:
        type: "string"
      mainCuisine:
        type: "string"
      mainDish:
        type: "string"
      imageList:
        type: "array"
        items:
          type: "string"
      status:
        type: "string"
        example: "PERMANENTLY_CLOSED"
        enum:
        - "OPEN"
        - "CLOSED"
        - "TEMPORARY_CLOSED"
        - "COMING_SOON"
        - "PERMANENTLY_CLOSED"
        - "NO_OPEN_HOUR"
      openTime:
        type: "string"
        example: "09.00 - 17.00 (Thu)"
      distance:
        type: "number"
        example: 0.7
      address:
        type: "string"
        example: "Plaza Indonesia Mall, Lt 3"
      menu:
        type: array
        items:
          $ref: "#/definitions/Photo"
      label:
        type: "array"
        items: 
          type: "string"
          enum:
          - "Trending"
          - "New"
    example:
      name: "Healthy Kitchen by Julius V"
      mainType: "Casual Dining"
      mainCuisine: "Vegetarian"
      mainDish: "Capcay"
      imageList:
      - "http://tny.im/jA-"
      - "http://tny.im/jA-"
      - "http://tny.im/jA-"
      status: "OPEN"
      openTime: "09.00 - 21.00 (Thu)"
      distance: 0.7
      address: "Senopati, Jakarta Selatan"
      menu: 
        - imagerUrl: "http://tny.im/jA-"
          category: "Menu"
          mainSubcategory: "Sub Category"
          subcategories: 
          - "subcategory 1"
          - "subcategory 2"
        - imagerUrl: "http://tny.im/jA-"
          category: "Menu"
          mainSubcategory: "Sub Category"
          subcategories: 
          - "subcategory 1"
          - "subcategory 2"    
      label:
      - "Trending"
      - "New" 
  OmniSearchRequest:
    type: "object"
    properties:
      query:
        type: "string"
        example: "boba"
      omniSearchTypes:
        type: "array"
        items:
          type: "string"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        omniSearchTypes:
        - "DISH"
        - "CUISINE"
        - "RESTAURANT_CHAIN"
        - "RESTAURANT"
        - "LOCATION"
        - "RESTAURANT_TYPE"
        query: "blahhh blahh"
      context:
        session: "session"
        clientInterface: "clientInterface"
  OmniSearchResponseItem:
    type: "object"
    properties:
      title:
        type: "string"
      subtitle:
        type: "string"
      iconUrl:
        type: "string"
        example: "https://img.qraved.co/v2/journal/wp-content/uploads/2015/02/esh-567x400-l.jpg"
      omniSearchType:
        type: "string"
        example: "RESTAURANT"
        enum:
        - "RESTAURANT"
        - "DISH"
        - "CUISINE"
        - "RESTAURANT_CHAIN"
        - "LOCATION"
      actionType:
        type: "string"
        example: "RESTAURANT"
        enum:
        - "SEARCH_RESULT"
        - "RESTAURANT"
        - "RESTAURANT_CHAIN"
        - "SEARCH_TEXT"
        - "SEARCH_RESULT_NEARBY"
        - "DEEPLINK"
        - "LANDING"
      restaurantId:
        type: "string"
        example: "221"
      searchSpec:
        type: "object"
        properties:
          geoDisplay:
            $ref: "#/definitions/GeoDisplay"
          filter:
            $ref: "#/definitions/SearchResultFilterBase"
      chainId:
        type: "string"
        example: "223"    
  OmniSearchResponse:
    type: "object"
    properties:
      results:
        type: "array"
        items:
          $ref: "#/definitions/OmniSearchResponseItem"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      results:
      - title: "Gandaria City, Jakarta"
        omniSearchType: "LOCATION"
        searchSpec:
          geoDisplay:
            name: "Gandaria City"
            locationType: "GEO"
            id: 23
      - title: "RM Makan Padang"
        subtitle: "53 OUTLETS JAKARTA BARAT"
        iconUrl: "https://www.gadjian.com/blog/wp-content/uploads/2018/01/Intip-Kesuksesan-Restoran-Padang-dengan-Sistem-Perjanjian-Kerja-Bagi-Hasil.jpg"
        omniSearchType: "RESTAURANT_CHAIN"
        chainId: "2431"
      - title: "Padang"
        subtitle: "Cuisine"
        omniSearchType: "CUISINE"
        searchSpec:
          filter:
            cuisine:
            - "CHINESE"
            - "WESTERN"
      - title: "Padang"
        subtitle: "sa-Dish"
        omniSearchType: "DISH"
        searchSpec:
          filter:
            dish:
            - "PIZZA"
            - "BURGER"
      - title: "Kopi Kenangan"
        subtitle: "Restaurant - Minuman"
        iconUrl: "https://awsimages.detik.net.id/community/media/visual/2019/06/25/4b2e9e97-a47e-49d3-8e20-26074032b26f_11.jpeg?w=700&q=80"
        omniSearchType: "RESTAURANT"
        restaurantId: "223"
      - title: "KFC Tanjung Duren"
        subtitle: "Restaurant - Tanjung Duren"
        iconUrl: "https://pbs.twimg.com/profile_images/3750210155/facf7e0f57bc8e7712f36b9a4e7d8bba_400x400.jpeg"
        omniSearchType: "RESTAURANT"
        restaurantId: "726"
  GalleryRequest:
    type: "object"
    properties: 
      data: 
        $ref: "#/definitions/GalleryRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
  GalleryRequestData:
    type: "object"
    required:
    - "restaurantId"
    properties:
      restaurantId:
        type: "string"
        example: "123"
    example: 
      restaurantId: "123"
  GalleryResponse:
    type: "object"
    required: 
    - "context"
    - "data"
    properties:
      data:
        type: "object"
        properties:
          restaurantName:
            type: "string"
            example: "Chir Chir Korean Fusion Chicken"
          highlightedLocation:
            type: "string"
            example: "PIK Jakarta"
          galleryItems:
            type: "array"
            items: 
              $ref: "#/definitions/GalleryItem"
      context:
        $ref: "#/definitions/ContextResponse"    
    example:
      data:
        restaurantName: "Chir Chir Korean Fusion Chicken"
        highlightedLocation: "PIK Jakarta"
        galleryItems:
        - category: "Food"
          subCategories: 
          - "Chicken Wings"
          - "Toppoki"
          - "Cheese"
          photoList:
          - imageUrl: "http://tny.im/jA-"
            category: "Food"
            mainSubcategory: "Chicken Wings"
            subcategories:
            - "Toppoki"
            - "Cheese"
        - category: "Ambience"
          subCategories: 
          - "Indoor"
          - "Outer"
          - "Inside"
          photoList:
          - imageUrl: "http://tny.im/jA-"
            category: "Indoor"
            mainSubcategory: "Indoor"
            subcategories:
            - "Indoor"
            - "Indoor"
          - imageUrl: "http://tny.im/jA-"
            category: "Outer"
            mainSubcategory: "Outer"
            subcategories:
            - "Outer"
            - "Outer"
  GalleryItem: 
    type: "object"
    required:
    - "category"
    - "photoList"
    properties:
      category:
        type: "string"
        example: "FOOD"
      subCategories:
        type: "array"
        items:
          type: "string"
      photoList:
        type: "array"
        items:
          $ref: "#/definitions/Photo"
    example:
      category: "Food"
      subCategories: 
      - "Chicken Wings"
      - "Toppoki"
      - "Cheese"
      photoList:
      - imageUrl: "http://tny.im/jA-"
        category: "Food"
        mainSubcategory: "Chicken Wings"
        subcategories:
        - "Toppoki"
        - "Cheese"
      - imageUrl: "http://tny.im/jA-"
        category: "Food"
        mainSubcategory: "Chicken Wings"
        subcategories:
        - "Toppoki"
        - "Cheese"
                
  GlossaryPageRequest:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/GeoRequestData"
      context:
        $ref: "#/definitions/ContextRequest"
    example:
      data:
        geoLocation:
          lon: 68.45
          lat: 23.44
        geoDisplay:
          name: "Jakarta"
          locationType: "GEO"
          id: 0
      context:
        session: "session"
        clientInterface: "clientInterface"
        
  GlossaryPageResponse:
    type: "object"
    required:
    - "data"
    properties:
      data:
        $ref: "#/definitions/GlossaryDataResponse"
        
  GlossaryDataResponse:
    type: "object"
    required:
    - "categories"
    properties:
      categories:
        type: array
        items: 
          $ref: "#/definitions/GlossaryCategory"
        
  GlossaryCategory:
    type: "object"
    required:
    - "name"
    - "items"
    properties:
      name:
        type: "string"
        example: "Italian"
      items: 
        $ref:  "#/definitions/GlossaryCategoryItem"
            
  GlossaryCategoryItem:
    type: "object"
    required:
    - "type"
    - "name"
    - "image"
    properties:
      type:
        type: "string"
      name:
        type: "string"
      image:
        type: "string"
        
    example:
        - type: "DISH"
          name: "PIZZA"
          image: "s3://323"
          
        - type: "CUISINE"
          name: "SALAD"
          image: "s3://1323"

